### ISSUE TITLE
Consolidating to one node type?

### ISSUE THREAD

**Issue by testbird** [Flowpack/Flowpack.Listable#1]
I find the `Sfi.Listable:Listable` name a little non-descriptive and it may not be neccessary.
What about only providing a `Sfi.Listable:List`?
If no wrapping elements are defined, the default behavior could be that of the current Listable node.

**Comment by dimaip** [comment]
Are you referring to TS object or to mixin?
There's already [`Sfi.Listable:List`](https://github.com/sfi-ru/Sfi.Listable/blob/master/Resources/Private/TypoScript/Api.ts2#L49), in addition to `Sfi.Listable:Listable`. It wraps `Sfi.Listable:Listable` with title and archive link. So Listable is the core of the package, and List is more like a convenience object.

**Comment by dimaip** [comment]
Ahh I think I understand what you mean now, to join two objects together.
Well no, I don't want to do it, as Listable is very abstract and low-level, it may be used in completely non-typical scenarios, not only in news. I want to keep it simple and only define some generic listing logic there.
List is an optional object, you may not want to use it at all, but instead of it use your own template for wrapping a list or something.

**Comment by testbird** [comment]
I appreciate that you want to keep the node configuration clean.

What difference would it make if the "List" object behaved exactly like "Listable" as long as none of its further parameters are defined? Maybe it already does. Then, you could also keep the user side a little cleaner by letting the basic documentation and examples start with presenting the "List" content node, and then mention the "Listable" as a more generic alternative for special integration purposes.

PS: When reading your docs I kept asking myself what you mean by Listable Node. I now understand it is kind of a BareList.

**Comment by dimaip** [comment]
> I appreciate that you want to keep the node configuration clean.

Which node configuration?

> What difference would it make if the "List" object behaved exactly like "Listable" as long as none of its further parameters are defined? Maybe it already does.

Well yes, it does, sort of. I think it just adds an extra div wrap without any class, but that's about it.

> Then, you could also keep the user side a little cleaner by letting the basic documentation and examples start with presenting the "List" content node, and then mention the "Listable" as a more generic alternative for special integration purposes.

The problem here is that I haven't figured an easy way for parent List object to pass down all its configuration to its Listable object. Need to fiddle with it a bit more.

Basically I treat Listable as a core of the package, the most generic thing that is relevant to all. And List is just a quick-n-dirty convenience object, the kind of thing which you need when you just need a title + archive link and don't want to spend time with custom templates. This package could do well without this object, maybe I should mention it more clearly, that it's all about Listable object, and everything else is just a helper.

Thanks a lot for your feedback. The version of this extension is not anywhere near to 1.0, so we can still experiment a lot with public API. I want it to become clear and expressive, but still stay low-level, more like a building block other can build upon, rather than a complete solution.

**Comment by testbird** [comment]
> Which node configuration?
> Sorry, I think I confused this with TS-Objects.

Thank you, at the end it may just be a wording issue. In case two separate objects have to remain, I think something like List vs. TitledList could more directly match what you explained to me.

**Comment by dimaip** [comment]
That's a good idea. We should think-through API better with next breaking release. Maybe I should rename the package itself to `List`?
